### PR TITLE
Fix/upgrade poetry version

### PR DESCRIPTION
**Pull request by SonnevilleDamien**
Update the docker image to use the latest version of [Poetry (1.2.0)](https://python-poetry.org).

### CODE REVIEW

**Review by ccamel — APPROVED** [review]
Great! Thx. 👍

**Review by amimart — APPROVED** [review]
Many thanks 🙏

**Review by hleonardtek — APPROVED** [review]
:+1:

**Review by ad2ien — APPROVED** [review]
:+1:

**Comment by ad2ien** [comment]
@SonnevilleDamien do you have the rights to merge?

**Comment by SonnevilleDamien** [comment]
> @SonnevilleDamien do you have the rights to merge?

**Pull request closed without merging**
